# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
ENABLE_LINTERS:
  - TSX_ESLINT
  - REPOSITORY_SECRETLINT
  - DOCKERFILE_HADOLINT
  - YAML_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - JSON_NPM_PACKAGE_JSON_LINT
  - JSON_PRETTIER
  - HTML_HTMLHINT
  - ENV_DOTENV_LINTER
  - BASH_SHELLCHECK
  - BASH_EXEC
  - BASH_SHFMT
  - REPOSITORY_CHECKOV
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_GIT_DIFF

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
VALIDATE_ALL_CODEBASE: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
